package org.launchcode.controllers;

import org.launchcode.models.Category;
import org.launchcode.models.Cheese;
import org.launchcode.models.data.CategoryDao;
import org.launchcode.models.data.CheeseDao;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.Errors;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import javax.validation.Valid;
import java.util.List;

@Controller
@RequestMapping("cheese")
public class CheeseController {

    // To instantiate (declare instances) of our CheeseDao that has extended CrudRepository,
    // we can use dependency injection, @Autowired.
    // Behind the scenes spring will do this:
    // public CheeseController(CheeseDao cheeseDao)
    //        this.cheeseDao = cheeseDao;
    @Autowired
    private
    CheeseDao cheeseDao;

    @Autowired
    private
    CategoryDao categoryDao;

    public CheeseController(CheeseDao cheeseDao, CategoryDao categoryDao) {
        this.cheeseDao = cheeseDao;
        this.categoryDao = categoryDao;
    }

    // Request path: /cheese
    @RequestMapping(value = "")

    // takes an object out of the db using Spring Data JPA (cheeseDao),
    // run it through Spring MVC to Thymeleaf layer where we had a list of POJOs
    // where we rendered that list to the webpage.
    // method binds data (list of cheeses) to the model
    public String index(Model model) {

        // findAll() is an iterable that Thymeleaf uses in th:each="cheese : ${cheeses}"
        model.addAttribute("cheeses", cheeseDao.findAll());
        model.addAttribute("title", "My Cheeses");

        return "cheese/index";
    }

    @RequestMapping(value = "add", method = RequestMethod.GET)
    public String displayAddCheeseForm(Model model) {
        model.addAttribute("title", "Add Cheese");
        // the default constructor defined in Cheese.java is used to construct new Cheese
        model.addAttribute(new Cheese());
        // need findAll() to display all the categories in the view in order
        // for the user to select one
        model.addAttribute("categories", categoryDao.findAll());
        return "cheese/add";
    }

    @RequestMapping(value = "add", method = RequestMethod.POST)
    // creates a new cheese
    public String processAddCheeseForm(@ModelAttribute  @Valid Cheese newCheese,
                                       Errors errors, @RequestParam int categoryId, Model model) {

        if (errors.hasErrors()) {
            model.addAttribute("title", "Add Cheese");
            model.addAttribute("categories", categoryDao.findAll());
            return "cheese/add";
        }
        // we need to have the Category object corresponding to this ID so we
        // can set the new cheese fields properly to that category. This will fetch a
        // single Category object with ID matching the CategoryId
        // findOne() retrieves the entity by the given Id from the data layer
        Category cat = categoryDao.findOne(categoryId);

        // So when data comes in from the view,
        // newCheese has id = 0, name = "cheddar", description = "cheddar cheese",
        // category = null.  Then use the category object to set newCheese with the
        // proper category id and other details. Id is generated by hibernate on save
        newCheese.setCategory(cat);
        cheeseDao.save(newCheese);
        return "redirect:";
    }

    @RequestMapping(value = "remove", method = RequestMethod.GET)
    public String displayRemoveCheeseForm(Model model) {
        model.addAttribute("cheeses", cheeseDao.findAll());
        model.addAttribute("title", "Remove Cheese");
        return "cheese/remove";
    }

    @RequestMapping(value = "remove", method = RequestMethod.POST)
    public String processRemoveCheeseForm(@RequestParam int[] cheeseIds) {

        // get category object from the data layer via categoryId that comes in
        // from the view
        for (int cheeseId : cheeseIds) {
            cheeseDao.delete(cheeseId);
        }
        return "redirect:";
    }

    // retrieve all cheeses in the given category and pass them into the view
    @RequestMapping(value = "category", method = RequestMethod.GET)
    public String category(Model model, @RequestParam int id) {

        Category cat = categoryDao.findOne(id);

        // retrieve all the cheeses out of cat (which holds one record) and stores them in cheeses
        List<Cheese> cheeses = cat.getCheeses();
        model.addAttribute("cheeses", cheeses);
        // displays Cheeses in Category: category name
        model.addAttribute("title", "Cheeses in Category: " + cat.getName());
        return "cheese/index";
    }
}